#!/bin/bash

case "$1" in
1)
	[[ -d ./lunar ]] || { echo "lunar-mnt error: Cannot find ./lunar"; exit 1; }
	cd lunar
	mount -v --bind /dev dev
	mount -v --bind /dev/pts dev/pts
	mount -v --bind /dev/shm dev/shm
	mount -v --bind /proc proc
	mount -v --bind /sys sys
	;;
0)
	[[ -d ./lunar ]] || { echo "lunar-mnt error: Cannot find ./lunar"; exit 1; }
	cd lunar
	umount -v dev
	umount -v dev/pts
	umount -v dev/shm
	umount -v proc
	umount -v sys
	;;
*)
	echo "Usage: lunar-mnt { 1 | 0 }"
	exit 22
	;;
esac

